-- Window
WINDOW_SCALE = 1
INITIAL_WINDOW_WIDTH, INITIAL_WINDOW_HEIGHT, WINDOW_FLAGS = love.window.getMode()
WINDOW_WIDTH, WINDOW_HEIGHT = INITIAL_WINDOW_WIDTH * WINDOW_SCALE, INITIAL_WINDOW_HEIGHT * WINDOW_SCALE
VIRTUAL_WIDTH, VIRTUAL_HEIGHT = WINDOW_WIDTH / WINDOW_SCALE, WINDOW_HEIGHT / WINDOW_SCALE
